[package]
name = "husky_voxel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
mlua = "0.6.1"

dot_vox = "4.1.0"
